### ISSUE TITLE
You don't need to describe this scenario

### ISSUE THREAD

**Issue by ghost** [AndrZakhara/js-array-class#15]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L75

 You describe scenario if callback is not a function, but you don't need to do it, because if you will pass not a function as an argument you'll get an error 'callback is not a function' by default.

**Comment by AndrZakhara** [comment]
I couldn't implement behavior of real array without it

**Comment by pseudopilot** [comment]
So, you use this scenario just to specify your Error message? Right?

**Comment by AndrZakhara** [comment]
Yep. And standart recomend to use human-readable description of the error.

**Comment by AndrZakhara** [comment]
In this case I handle type error like in an original js array
