### ISSUE TITLE
You dont need this variable

### ISSUE THREAD

**Issue by ghost** [AndrZakhara/js-array-class#17]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L133

**Comment by AndrZakhara** [comment]
Can you give me an examle?

**Comment by pseudopilot** [comment]
You may just write
`stringResult += this[i] + ','`
you don't use this ',' anymore, so there is no necessity to create a variable just for one comma.

**Comment by AndrZakhara** [comment]
Yep, I did it in the first implementation but linter...

**Comment by pseudopilot** [comment]
Try 
```
stringResult += `${this[i]},`
...
```

**Comment by AndrZakhara** [comment]
agree with you, thanks
