### ISSUE TITLE
You have to put this FOR after line 6 inside IF

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#18]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L11

Because now if you create new MyArray(6) - it'll create an array with first element 6.

**Comment by AndrZakhara** [comment]
I can't put fot into if! 
I added an additional condition to fix bug.
    for (let i = 0; i < this.length; i++) {
      this[i] = rest.length === 1 && typeof rest[0] === 'number' ? i : rest[i];
    }

**Comment by pseudopilot** [comment]
I think I was mistaking giving this recomendation. The right decision, I think, is to put this FOR loop in additinal `else if`
