### ISSUE TITLE
You don't need to check thisArg

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#19]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L20

If thisArgument is not passed as argument  - undefined should be passed. So, you my just write 
newArray[i] = callback.call(thisArg, arrayLike[i], i, arrayLike).

And do it everywhere in your code.

**Comment by AndrZakhara** [comment]
To my mind, better: from(arrayLike, callback, thisArg = this) {}
I fix it.
