### ISSUE TITLE
You may set lenght only one time after cycle

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#20]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L31

So, you don't need to increase it by 1 at each iteration.

**Comment by AndrZakhara** [comment]
I can  increase the length in a loop only.

**Comment by pseudopilot** [comment]
Why? You definitely know the length of your future array in method FROM. It's equal to your `arrayLike.length`.
So you can just set the length after loop like this:
 `newArray.length = arrayLike.length`

**Comment by AndrZakhara** [comment]
fixed
