### ISSUE TITLE
Use initialValue === undefined instead of !initialValue

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#22]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L88

Now if the value of initialValue is 0, you'll get an Error, because 0 will be transformed into false.
In next IF change it too.

**Comment by AndrZakhara** [comment]
I expect from this condition exactly this behavior. If  the value of initialValue is 0, i check it later in my code.

**Comment by pseudopilot** [comment]
I think you won't be able to check it later if it's 0 here: 
```
if (this.length === 0 && initialValue) {
      return initialValue;
}
```
because the mistake will be thrown, so your code will stop to execute. No?
