### ISSUE TITLE
You may remove lines 92-98

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#24]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L92

You'll get the same result without these IF blocks, because then you set the value of acc and pass into FOR.

**Comment by AndrZakhara** [comment]
Give me an example how I could implement it. In my point of view I have to use this condition

**Comment by pseudopilot** [comment]
Okay, for example, you don't do this check, but you have only one member in array (lets say 5) and no initial value
```
if (this.length === 1 && !initialValue) {
      return this[0];
}
```

so, then you don't return this[0] value. In this case further you have another check:
`let accumulator = typeof initialValue !== 'undefined' ? initialValue : this[0];`

So, you initial value is undefined, and now your accumulator is this[0]

Then you have next check:
`let i = typeof initialValue !== 'undefined' ? 0 : 1;`

so initial value is undefined and your i now is 1.

Then you have a cycle:
```
for (i; i < this.length; i++) {
      accumulator = callback(accumulator, this[i], i, this);
}
```
But it won't work because you i is 1 and it is not lower than this.length
So, your function returns accumulator. And it is this[0].

In lines 96 - 98 - the same situation. Just follow the chain.

**Comment by AndrZakhara** [comment]
thanks for your comment

**Comment by AndrZakhara** [comment]
fixed
