### ISSUE TITLE
You don't need this line  let context = null;

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#25]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L111

Because next step you set the value of this variable as this or thisArg.
But as I wrote earlier you don't even need to set this variable, you may pass thisArg directly into callback function.

**Comment by AndrZakhara** [comment]
fixed
