### ISSUE TITLE
You may avoid using variable BOOLEAN

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#26]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L121

You can just put *callback.call(context, this[i], i, this)* as condition for IF without creating boolean, because if transform into boolean automatically.
If you still want to use this variable, you'd better give it more understandable name, for example, isTarget

**Comment by AndrZakhara** [comment]
Thank you, I agree with you

**Comment by AndrZakhara** [comment]
fixed
