### ISSUE TITLE
You may optimize your sort method adding a FLAG

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#27]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L146

Your method will do a lot of iteration anyway, even if your array is already sorted. So, you should use a flag (additional paremeter) which will stop further iterations if there is no changes in array after current iteration.

**Comment by AndrZakhara** [comment]
I'll try to do it on the weekend
