### ISSUE TITLE
You don't need to create new array for find function

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#29]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L177

Just look for target element in THIS object

**Comment by AndrZakhara** [comment]
I have to use elements from array copy in my implementation (The range of elements processed by find is set before the first call to callbackfn. Elements that are appended to the array after the call to find begins will not be visited by callbackfn. If existing elements of the array are changed, their value as passed to predicate will be the value at the time that find visits them. https://www.ecma-international.org/ecma-262/6.0/). I can't do it without array copy.

find(callback, thisArg = this) {
    const initialArray = thisArg.map(i => i);
    if (callback && typeof callback === 'function') {
      for (let i = 0; i < initialArray.length; i++) {
        if (callback.call(thisArg, initialArray[i], i, thisArg)) {
          return initialArray[i];
        }
      }
    } else {
      const message = `${callback} is not a function at MyArray.map`;
      throw new TypeError(message);
    }
    return undefined;
  }
read about in in the standart

**Comment by AndrZakhara** [comment]
thanks, fixed

**Comment by pseudopilot** [comment]
You was right about the length. We should fix the length of our initial array and the quantity of iterations in FIND method should be equal to initial length. So, if callback function adds or deletes some elements of array - we still have to check LENGHT members of array. But if callback function changes the values of initial array - it has to be taken into consideration.
Actually, I have to correct my FIND method as well. And probably, forEACH and some other methods need the same...

**Comment by AndrZakhara** [comment]
all methods with collback function

**Comment by pseudopilot** [comment]
Let's wait for Timofey's opinion about it )) Because if we do need it - everybody should correct their methods. But maybe it won't be so critical.

**Comment by AndrZakhara** [comment]
We discussed this issue with colleagues in the morning. In general, most of them understood it.

**Comment by motifej** [comment]
```const initialArray = context.map(i => i);```  - looks too strange!
you have to use it like this: ```callback.call(context, this[i], i, this)```

**Comment by AndrZakhara** [comment]
Yes, I fix it earlier.
