### ISSUE TITLE
Check if absolute values of begin and end are > length

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#30]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L194

Now you'll get an array with some empty (undefined) elements. But you won't get them in original array in this case.
Just try to create array with length 5 and set begin === -7

**Comment by AndrZakhara** [comment]
Understand your idea, thanks
