### ISSUE TITLE
You should correct your ternary operator

### ISSUE THREAD

**Issue by pseudopilot** [AndrZakhara/js-array-class#31]
https://github.com/AndrZakhara/js-array-class/blob/3931c9545ced4874eb6a152e238565824d8a4c24/src/index.js#L20

I thought Alexandr has already wrote you about it, but can't see this issue in the list.
Instead of
`thisArg === undefined ? context = arrayLike : context = thisArg;`
you should write
`context = thisArg === undefined ?arrayLike : thisArg;`

So, you just put `context =` in ther very begining

You use this configuration a number of time

**Comment by AndrZakhara** [comment]
I delete and rewright it in the following way: function foo(thisArg = this) {}. I think it's better.
